# Run a program and capture stdout to a file (portable; no shell redirect).
if(NOT DEFINED MACEMU_REDIRECT_TOOL OR NOT DEFINED MACEMU_REDIRECT_OUTPUT)
  message(FATAL_ERROR "run_redirect.cmake requires MACEMU_REDIRECT_TOOL and MACEMU_REDIRECT_OUTPUT")
endif()
if(DEFINED MACEMU_REDIRECT_ARGS)
  separate_arguments(MACEMU_REDIRECT_ARG_LIST NATIVE_COMMAND "${MACEMU_REDIRECT_ARGS}")
else()
  set(MACEMU_REDIRECT_ARG_LIST)
endif()
if(DEFINED MACEMU_REDIRECT_WORKDIR)
  set(MACEMU_REDIRECT_WORKING_DIRECTORY WORKING_DIRECTORY "${MACEMU_REDIRECT_WORKDIR}")
else()
  set(MACEMU_REDIRECT_WORKING_DIRECTORY)
endif()
execute_process(
  COMMAND "${MACEMU_REDIRECT_TOOL}" ${MACEMU_REDIRECT_ARG_LIST}
  OUTPUT_FILE "${MACEMU_REDIRECT_OUTPUT}"
  RESULT_VARIABLE MACEMU_REDIRECT_EXIT_CODE
  ${MACEMU_REDIRECT_WORKING_DIRECTORY}
)
if(NOT MACEMU_REDIRECT_EXIT_CODE EQUAL 0)
  message(FATAL_ERROR "${MACEMU_REDIRECT_TOOL} failed with exit code ${MACEMU_REDIRECT_EXIT_CODE}")
endif()
